config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :status, presence: true, length: { maximum: 10 }
    validates :content, presence: true, length: { maximum: 255 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum:50 }
  validates :email, presence: true, length: { maximum:255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  def require_login
    unless logged_in?
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  
  def index
    @tasks = current_user.tasks.all.page(params[:page]).per(2)
  end
  
  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'タスクが登録されました。'
      redirect_to tasks_url
    else
      flash.now[:danger] = 'タスクが登録できませんでした。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @task.update(task_params)
      flash[:success] = "タスクID:#{@task.id}を修正しました。"
      redirect_to tasks_url
    else
      flash.now[:danger] = 'タスクを修正できませんでした。'
      render :edit
    end
  end
  
  def destroy
    
    @task.destroy
    
    flash[:success] = 'タスクは削除されました。'
    redirect_to tasks_url
      
  end
  
  
  private
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザー登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました。'
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

    <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
    <% if task.errors.any? %>
    <div id="error_explanation">
        <ul>
            <% task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <%= f.label :status, 'ステータス' %>
    <%= f.text_field :status %>
    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content %>
    <%= f.submit '登録' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<%= render 'form', task: @task %>

<%= link_to 'タスク一覧へ戻る', tasks_path %>
    

app/views/tasks/index.html.erb
<% if logged_in? %>
  <h1>タスク一覧</h1>
  
  <p><%= current_user.name %> としてログイン中</p>
  
  <ul>
    <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> : <%= task.content %> (<%= task.status %>)</li>
    <% end %>
  </ul>
  
  <%= paginate @tasks %>
  
  <%= link_to '新規タスクの登録', new_task_path %>
  <%= link_to 'ログアウト', session_path(id: current_user), method: :delete %>

  
<% end %>

app/views/tasks/new.html.erb
<h1>新規タスク登録</h1>

<%= render 'form', task: @task %>
<%= link_to 'タスク一覧へ戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>タスクID: <%= @task.id %> の内容</h1>

<p>ステータス: <%= @task.status %></p>
<p>タスク: <%= @task.content %></p>

<%= link_to 'タスク一覧へ戻る', tasks_path %>
<%= link_to 'タスクの編集', edit_task_path(@task) %>
<%= link_to 'タスクの削除', @task, method: :delete, data: { confirm: '本当に削除しますか？' } %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<div>
  <%= form_with(model: @user, local: true) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  
    <%= f.label :name, '名前' %>
    <%= f.text_field :name %>
    <%= f.label :email, 'メール' %>
    <%= f.email_field :email %>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation %>
    
    <%= f.submit 'ユーザー登録' %>
  <% end %>
</div>

<%= link_to 'ログイン', new_session_path %>